#!/bin/bash

# vim: set ts=4 sw=4 expandtab :

# Copyright (c) 2017 Timothy Savannah - All Rights Reserved
#   This code is licensed under the terms of the APACHE license version 2.0
#
# aur-buildpkg - Builds and installs one or more packages.
#   Run as regular user, and provide as arguments a list of packages



echoerr() {
    echo "$@" >&2
}

if [ "$1" = "--help" ];
then
    cat -- >&2 <<EOT
Usage: aur-buildpkg [packageName]
  Downloads and builds a given package from AUR

EOT
    exit 0;
fi




if [ "$1" != "_secret_arg_" ];
then
    BUILD_AS="$(whoami)"
    if [ "$BUILD_AS" = "root" ];
    then
        echoerr "You must run aur-buildpkg as a non-root user (to build the package)."
        exit 1;
    fi
    if [ $# -eq 0 ];
    then
        echoerr "Missing package name(s)."
        exit 1;
    fi
    
    if ( which sudo >/dev/null 2>&1 );
    then
        sudo $0 "_secret_arg_" "${BUILD_AS}" "$@";
        exit $?
    else
        echo "Login as root:"
        su root -c "$0 _secret_arg_ ${BUILD_AS} $@";
        exit $?
    fi
fi

shift; # _secret_arg_

BUILD_AS="${1}"

shift # BUILD_AS


if [ $# -gt 1 ];
then
    FAILED=
    for arg in "$@";
    do
        $0 "_secret_arg_" "${BUILD_AS}" "$arg"
        if [ $? -ne 0 ];
        then
            FAILED="$FAILED $arg"
        fi
    done
    if [ ! -z "$FAILED" ];
    then
        echo "Following packages failed: $FAILED"
        exit 2
    fi
    exit 0
fi


exiterr() {
    echo "[$PKGNAME] (`date`) $1" >&2
    exit 2
}

if [ ! -d "/usr/src/arch" ];
then
    mkdir -p '/usr/src/arch'
fi
chgrp users /usr/src/arch
chmod 2775 /usr/src/arch

cd /usr/src/arch


PKGNAME="$1"

su "${BUILD_AS}" aur-getpkg "${1}"
if [ $? -ne 0 ];
then
    echo "Failed to get '${1}'"
fi

pushd "/usr/src/arch/$PKGNAME"
su "${BUILD_AS}" /usr/bin/makepkg || exiterr "makepkg failed"
pacman -U --noconfirm *.pkg.tar.* || exiterr "Failed to install"
popd

# vim: set ts=4 sw=4 expandtab :
